Repository EAT-SSU/EATSSU-iOS, pull requests merged in 2024-06, with the labels that each got.

#6 [#5] Rx Dynamic 제거
  EatSSU-iOS/EatSSU-iOS.xcodeproj/project.pbxproj
Labels: Fix

#8 [#7] 폴더 세팅 완료
  EatSSU-iOS/EatSSU-iOS.xcodeproj/project.pbxproj
  EatSSU-iOS/EatSSU-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  EatSSU-iOS/Migration/Source/App/AppDelegate.swift
  EatSSU-iOS/Migration/Source/App/SceneDelegate.swift
  EatSSU-iOS/Migration/Source/Core/Base/File.swift
  EatSSU-iOS/Migration/Source/Core/Enum/File.swift
  EatSSU-iOS/Migration/Source/Core/Extension/File.swift
  EatSSU-iOS/Migration/Source/Core/Util/File.swift
  EatSSU-iOS/Migration/Source/Data/File.swift
  EatSSU-iOS/Migration/Source/Domain/File.swift
  EatSSU-iOS/Migration/Source/Presentation/Auth/File.swift
  EatSSU-iOS/Migration/Source/Presentation/Home/File.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/File.swift
  EatSSU-iOS/Migration/Source/Presentation/Review/File.swift
Labels: Setting

#12 [#11] Release.config 파일 메타 데이터 추가
  EatSSU-iOS/EatSSU-iOS.xcodeproj/project.pbxproj
  EatSSU-iOS/EatSSU-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Fix

#15 [#13] 마이페이지에 해당하는 View 코드를 MVVM에 적합하게 수정
  EatSSU-iOS/EatSSU-iOS.xcodeproj/project.pbxproj
  EatSSU-iOS/Migration/Source/Presentation/MyPage/F.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/DeletaAccountConfirmation/View/MigratedDeleteAccountConfirmationView.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/DeletaAccountConfirmation/View/MigratedDeleteAccountConfirmationViewController.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/MyReview/View/MigratedMyReviewView.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/MyReview/View/MigratedMyReviewViewController.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/Provision/View/MigratedProvisionView.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/Provision/View/MigratedProvisionViewController.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/Request/View/MigratedRequestView.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/Request/View/MigratedRequestViewController.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/View/MigratedMyPageServiceCell.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/View/MigratedMyPageView.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/View/MigratedMyPageViewController.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/View/MyPageModel/MigratedMyPageLocalData.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/View/MyPageModel/MigratedMyPageRightItemData.swift
Labels: Feat

#16 [#14] 사용자 인증 소스코드를 MVVM의 View 계층에 부합한 부분으로 설계
  EatSSU-iOS/EatSSU-iOS.xcodeproj/project.pbxproj
  EatSSU-iOS/Migration/Source/Presentation/Auth/I.swift
  EatSSU-iOS/Migration/Source/Presentation/Auth/SubViews/View/MigratedSetNickNameView.swift
  EatSSU-iOS/Migration/Source/Presentation/Auth/SubViews/View/MigratedSetNickNameViewController.swift
  EatSSU-iOS/Migration/Source/Presentation/Auth/View/MigratedLoginView.swift
  EatSSU-iOS/Migration/Source/Presentation/Auth/View/MigratedLoginViewController.swift
Labels: Feat

#29 [#27] #26 PR까지 병합된 변경사항을 반영하여 Xcode가 열리지 않는 문제 해결
  EatSSU-iOS/EatSSU-iOS.xcodeproj/project.pbxproj
  EatSSU-iOS/Migration/Source/Presentation/Auth/I.swift
  EatSSU-iOS/Migration/Source/Presentation/Auth/SubViews/View/MigratedSetNickNameView.swift
  EatSSU-iOS/Migration/Source/Presentation/Auth/SubViews/View/MigratedSetNickNameViewController.swift
  EatSSU-iOS/Migration/Source/Presentation/Auth/View/MigratedLoginView.swift
  EatSSU-iOS/Migration/Source/Presentation/Auth/View/MigratedLoginViewController.swift
  EatSSU-iOS/Migration/Source/Presentation/Auth/ViewModel/MigratedLoginViewModel.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/F.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/DeletaAccountConfirmation/View/MigratedDeleteAccountConfirmationView.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/DeletaAccountConfirmation/View/MigratedDeleteAccountConfirmationViewController.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/MyReview/View/MigratedMyReviewView.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/MyReview/View/MigratedMyReviewViewController.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/Provision/View/MigratedProvisionView.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/Provision/View/MigratedProvisionViewController.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/Request/View/MigratedRequestView.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/Request/View/MigratedRequestViewController.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/View/MigratedMyPageServiceCell.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/View/MigratedMyPageView.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/View/MigratedMyPageViewController.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/View/MyPageModel/MigratedMyPageLocalData.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/View/MyPageModel/MigratedMyPageRightItemData.swift
Labels: Fix

#32 [#25] SetNicknameViewModel 설계 + 레거시 코드의 메타데이터 수정
  EatSSU-iOS/EatSSU-iOS.xcodeproj/project.pbxproj
  EatSSU-iOS/EatSSU-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  EatSSU-iOS/EatSSU-iOS/MyPage/ViewController/MyPageViewController.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/Cell/MyPageServiceCell.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/Model/MyPageModel.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/View/DeleteAccountConfirmationView.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/View/MyPageView.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/View/MyReviewView.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/View/NoticeTableViewCell.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/View/ProvisionView.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/View/RequestView.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/ViewController/DeleteAccountConfirmationViewController.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/ViewController/MyPageViewController.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/ViewController/MyReviewViewController.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/ViewController/NoticeViewController.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/ViewController/ProvisionViewController.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/ViewController/RequestViewController.swift
  EatSSU-iOS/Migration/Source/Presentation/Auth/SubViews/View/MigratedSetNickNameView.swift
  EatSSU-iOS/Migration/Source/Presentation/Auth/SubViews/View/MigratedSetNickNameViewController.swift
  EatSSU-iOS/Migration/Source/Presentation/Auth/SubViews/ViewModel/MigratedSetNicknameViewModel.swift
Labels: Feat

#36 [#25] SetNicknameViewModel 설계 + 레거시 코드의 메타데이터 수정
  EatSSU-iOS/EatSSU-iOS.xcodeproj/project.pbxproj
  EatSSU-iOS/EatSSU-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  EatSSU-iOS/EatSSU-iOS/MyPage/ViewController/MyPageViewController.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/Cell/MyPageServiceCell.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/Model/MyPageModel.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/View/DeleteAccountConfirmationView.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/View/MyPageView.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/View/MyReviewView.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/View/NoticeTableViewCell.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/View/ProvisionView.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/View/RequestView.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/ViewController/DeleteAccountConfirmationViewController.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/ViewController/MyPageViewController.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/ViewController/MyReviewViewController.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/ViewController/NoticeViewController.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/ViewController/ProvisionViewController.swift
  EatSSU-iOS/EatSSU-iOS/Screen/MyPage/ViewController/RequestViewController.swift
  EatSSU-iOS/Migration/Source/Presentation/Auth/SubViews/View/MigratedSetNickNameView.swift
  EatSSU-iOS/Migration/Source/Presentation/Auth/SubViews/View/MigratedSetNickNameViewController.swift
  EatSSU-iOS/Migration/Source/Presentation/Auth/SubViews/ViewModel/MigratedSetNicknameViewModel.swift
Labels: Feat

#37 [#21] RequestViewModel 설계 완료
  EatSSU-iOS/EatSSU-iOS.xcodeproj/project.pbxproj
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/Request/New Group/MigratedRequestViewModel.swift
  EatSSU-iOS/Migration/Source/Presentation/MyPage/SubViews/Request/View/MigratedRequestViewController.swift
Labels: Feat

#39 [#38] Swift Format 제거
  EatSSU-iOS/EatSSU-iOS.xcodeproj/project.pbxproj
  EatSSU-iOS/EatSSU-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Fix
